const defaultSourcePage = "pelayanan-akuntansi";

const jasaAkuntansiKeywords = [
    "jasa akuntansi profesional",
    "layanan pembukuan usaha",
    "jasa laporan keuangan",
    "akuntan untuk UMKM",
    "konsultan akuntansi bisnis",
    "jasa audit keuangan",
    "akuntansi perusahaan kecil",
    "jasa accounting bulanan",
    "jasa pencatatan transaksi",
    "laporan laba rugi usaha",
    "jasa penyusunan neraca",
    "akuntansi pajak bulanan",
    "jasa keuangan bisnis",
    "pembuatan laporan keuangan",
    "jasa akuntansi murah",
    "akuntansi dan pajak",
    "akuntansi profesional freelance",
    "jasa input data akuntansi",
    "akuntansi perusahaan dagang",
    "jasa closing bulanan",
    "jasa laporan arus kas",
    "konsultan laporan keuangan",
    "jasa pembukuan online",
    "layanan akuntansi digital",
    "pembukuan bisnis kecil",
    "jasa audit internal",
    "akuntansi startup",
    "jasa pencatatan keuangan",
    "akuntansi untuk legalitas usaha",
    "akuntan publik terpercaya"
];

const AccountantPackagesRaw = [
    {
        type: "Jasa Akuntansi (Kontrak) Omzet Kurang dari 2,5 M (1 Tahun)",
        price: 800000,
        priceOriginal: 1250000, // price = priceOriginal * (1 - discount)
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%20Kurang%20dari%202,5%20M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 2,5M s/d 5M (1 Tahun)",
        price: 1300000,
        priceOriginal: 2031250,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%202,5M%20s/d%205M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 5M s/d 7,5M (1 Tahun)",
        price: 1800000,
        priceOriginal: 2812500,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%205M%20s/d%207,5M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 7,5M s/d 10M (1 Tahun)",
        price: 2300000,
        priceOriginal: 3593750,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%207,5M%20s/d%2010M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 10M s/d 12,5M (1 Tahun)",
        price: 2800000,
        priceOriginal: 4375000,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%2010M%20s/d%2012,5M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 12,5M s/d 15M (1 Tahun)",
        price: 3300000,
        priceOriginal: 5156250,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%2012,5M%20s/d%2015M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 15M s/d 17,5M (1 Tahun)",
        price: 3800000,
        priceOriginal: 5937500,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%2015M%20s/d%2017,5M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 17,5M s/d 20M (1 Tahun)",
        price: 4300000,
        priceOriginal: 6718750,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%2017,5M%20s/d%2020M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 20M s/d 25M (1 Tahun)",
        price: 4800000,
        priceOriginal: 7500000,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%2020M%20s/d%2025M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
    {
        type: "Jasa Akuntansi (Kontrak) Omzet 25M s/d 30M (1 Tahun)",
        price: 5300000,
        priceOriginal: 8281250,
        discount: 36,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo!%20Saya%20mau%20konsultasi%20terkait%20Jasa%20Akuntansi%20(Kontrak)%20Omzet%2025M%20s/d%2030M%20(1%20Tahun)!",
        features: [
            { feature: "Jurnal Keuangan", status: true },
            { feature: "Buku Besar", status: true },
            { feature: "Laporan Neraca Keuangan", status: true },
            { feature: "Laporan Laba / Rugi Keuangan", status: true },
            { feature: "Jurnal Penyesuaian", status: true },
            { feature: "Rekonsiliasi Bank", status: true },
            { feature: "Buku Besar Pembantu", status: true },
        ],
        requirements: [
            "Mutasi Rekening Bank",
            "Rekap Pengeluaran",
            "Rekap Pemasukan",
            "Rekap AP (Account Payable)",
            "Rekap AR (Account Receivable)",
            "Daftar Asset Perusahaan",
            "Daftar Gaji Karyawan",
            "Rekap Pajak Perusahaan",
            "Stock Perusahaan (Jika Perusahaan Dagang)",
        ],
    },
];

export const AccountantPackages = AccountantPackagesRaw.map((pkg) => ({
    ...pkg,
    sourcePage: pkg.sourcePage || defaultSourcePage,
    keywords: pkg.keywords?.length ? pkg.keywords : jasaAkuntansiKeywords,
}));