export const CVPackages = [
    {
        type: "CV Dasar",
        price: 3000000,
        priceOriginal: 4710000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20CV%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Efin Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L dan  SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: false },
            { feature: "Logo Perusahaan", status: false },
            { feature: "Company Profil", status: false },
            { feature: "Kartu Nama", status: false },
            { feature: "Invoice", status: false },
            { feature: "Website Company", status: false },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: false },
            { feature: "Serifikat Elektronik", status: false }
        ]
    },
    {
        type: "CV Lengkap",
        price: 3500000,
        priceOriginal: 5495000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20CV%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Efin Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L dan  SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profil", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Website Company", status: false },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: false },
            { feature: "Serifikat Elektronik", status: false }
        ]
    },
    {
        type: "CV Lengkap + PKP",
        price: 4500000,
        priceOriginal: 7065000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20CV%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Efin Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L dan  SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profil", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: true },
            { feature: "Serifikat Elektronik", status: true },
            { feature: "Website Company", status: false }
        ]
    },
    {
        type: "CV Lengkap + Website Company",
        price: 6800000,
        priceOriginal: 7800000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20CV%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Efin Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L dan  SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profil", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Website Company", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: false },
            { feature: "Serifikat Elektronik", status: false }
        ]
    },
    {
        type: "CV Lengkap + PKP + Website",
        price: 7800000,
        priceOriginal: 9420000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20CV%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Efin Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L dan  SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profil", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Website Company", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: true },
            { feature: "Serifikat Elektronik", status: true }
        ]
    }
];
