export const PTPackages = [
    {
        type: "PT DASAR",
        highlight: true,
        price: 4500000,
        priceOriginal: 8550000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L, Tata Ruang dan SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Account Gmail", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: false },
            { feature: "Logo Perusahaan", status: false },
            { feature: "Company Profile", status: false },
            { feature: "Kartu Nama", status: false },
            { feature: "Invoice", status: false },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: false },
            { feature: "Sertifikat Elektronik", status: false },
            { feature: "Website Company", status: false },
            { feature: "Logo Perusahaan", status: false }
        ]
    },
    {
        type: "PT LENGKAP",
        highlight: true,
        price: 5000000,
        priceOriginal: 9500000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L, Tata Ruang dan SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Account Gmail", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profile", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: false },
            { feature: "Sertifikat Elektronik", status: false },
            { feature: "Website Company", status: false },
            { feature: "Logo Perusahaan", status: false }
        ]
    },
    {
        type: "PT LENGKAP + PKP",
        highlight: false,
        price: 6000000,
        priceOriginal: 11400000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L, Tata Ruang dan SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Account Gmail", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profile", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: true },
            { feature: "Sertifikat Elektronik", status: true },
            { feature: "Website Company", status: false },
            { feature: "Logo Perusahaan", status: false }
        ]
    },
    {
        type: "PT LENGKAP + WEBSITE COMPANY",
        highlight: true,
        price: 7300000,
        priceOriginal: 10205000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L, Tata Ruang dan SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Account Gmail", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profile", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Website Company", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: false },
            { feature: "Sertifikat Elektronik", status: false }
        ]
    },
    {
        type: "PT LENGKAP + PKP + WEBSITE COMPANY",
        highlight: false,
        price: 7800000,
        priceOriginal: 10990000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L, Tata Ruang dan SPPL )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Account Gmail", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
            { feature: "Kop Surat", status: true },
            { feature: "Logo Perusahaan", status: true },
            { feature: "Company Profile", status: true },
            { feature: "Kartu Nama", status: true },
            { feature: "Invoice", status: true },
            { feature: "Website Company", status: true },
            { feature: "Surat Pengukuhan Kena Pajak ( SPPKP )", status: true },
            { feature: "Sertifikat Elektronik", status: true }
        ]
    },
    {
        type: "PAKET SILVER PT PERORANGAN",
        highlight: false,
        price: 600000,
        priceOriginal: 942000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Pesan Nama PT Perorangan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "Surat Pernyataan Kemenkumham", status: true },
            { feature: "NPWP PT Perorangan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak PT (SKT)", status: true },
            { feature: "Nomor Induk Berusaha (NIB)", status: true },
            { feature: "Pernyataan Mandiri OSS (K3L, Tata Ruang dan SPPL)", status: true },
            { feature: "Sertifikat Standar (Jika resiko KBLI Menengah Rendah)", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Email PT Perorangan", status: true },
            { feature: "Free Stempel PT Perorangan", status: true },
            { feature: "Kop Surat", status: false },
            { feature: "Logo Perusahaan", status: false },
            { feature: "Company Profile", status: false },
            { feature: "Kartu Nama", status: false },
            { feature: "Invoice", status: false },
            { feature: "Surat Pengukuhan Kena Pajak (SPPKP)", status: false },
            { feature: "Sertifikat Elektronik", status: false },
            { feature: "Website Company", status: false }
        ]
    },
    {
        type: "PAKET GOLD PT PERORANGAN",
        highlight: false,
        price: 1500000,
        priceOriginal: 2350000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Pesan Nama PT Perorangan", status: true },
            { feature: "Akta Penegasan Pendirian", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "Surat Pernyataan Kemenkumham", status: true },
            { feature: "NPWP PT Perorangan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak PT (SKT)", status: true },
            { feature: "Nomor Induk Berusaha (NIB)", status: true },
            { feature: "Pernyataan Mandiri OSS (K3L, Tata Ruang dan SPPL)", status: true },
            { feature: "Sertifikat Standar (Jika resiko KBLI Menengah Rendah)", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Email PT Perorangan", status: true },
            { feature: "Free Stempel PT Perorangan", status: true },
            { feature: "Kop Surat", status: false },
            { feature: "Logo Perusahaan", status: false },
            { feature: "Company Profile", status: false },
            { feature: "Kartu Nama", status: false },
            { feature: "Invoice", status: false },
            { feature: "Surat Pengukuhan Kena Pajak (SPPKP)", status: false },
            { feature: "Sertifikat Elektronik", status: false },
            { feature: "Website Company", status: false }
        ]
    }
];

export const PMAPackages = [
    {
        type: "PT PMA (Penanaman Modal Asing)",
        highlight: true ,
        price: 8500000,
        priceOriginal: 11625000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pembuatan%20PT%20PMA%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Akta Pendirian Perusahaan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Badan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak ( SKT )", status: true },
            { feature: "Coretax Badan", status: true },
            { feature: "Nomor Induk Berusaha ( NIB )", status: true },
            { feature: "Pernyataan Mandiri OSS ( K3L dan  SPPL )", status: true },
            { feature: "KKKPR ( Konfirmasi Kesesuaian Kegiatan Pemanfaatan Ruang )", status: true },
            { feature: "Sertifikat Standar ( Jika resiko KBLI Menengah Rendah )", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Stempel Nama Perusahaan", status: true },
            { feature: "Free Template Laporan Keuangan", status: true },
        ]
    }
];

export const BadanUsahaPackages = [
    {
        type: "Pendirian Yayasan",
        highlight: false,
        price: 4000000,
        priceOriginal: 6820000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pendirian%20Yayasan%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Pesan Nama Yayasan", status: true },
            { feature: "Akta Pendirian Yayasan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Yayasan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak Yayasan (SKT)", status: true },
            { feature: "Nomor Induk Berusaha (NIB)", status: true },
            { feature: "Pernyataan Mandiri OSS (K3L, Tata Ruang dan SPPL)", status: true },
            { feature: "Sertifikat Standar (Jika resiko KBLI Menengah Rendah)", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Email Yayasan", status: true },
            { feature: "Free Stempel Nama Yayasan", status: true }
        ]
    },
    {
        type: "Pendirian Perkumpulan/Asosiasi",
        highlight: false,
        price: 4000000,
        priceOriginal: 6820000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pendirian%20Asosiasi/Perkumpulan%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Pesan Nama Perkumpulan", status: true },
            { feature: "Akta Pendirian Yayasan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Yayasan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak Yayasan (SKT)", status: true },
            { feature: "Nomor Induk Berusaha (NIB)", status: true },
            { feature: "Pernyataan Mandiri OSS (K3L, Tata Ruang dan SPPL)", status: true },
            { feature: "Sertifikat Standar (Jika resiko KBLI Menengah Rendah)", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Email Perkumpulan", status: true },
            { feature: "Free Stempel Nama Perkumpulan", status: true }
        ]
    },
    {
        type: "Pendirian Firma Hukum",
        highlight: false,
        price: 3000000,
        priceOriginal: 4710000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pendirian%20Firma%20Hukum%20nih!%20",
        discount: 36,
        features: [
            { feature: "Free Konsultasi", status: true },
            { feature: "Pesan Nama Firma Hukum", status: true },
            { feature: "Akta Pendirian Perkumpulan", status: true },
            { feature: "Surat Keputusan Kemenkumham", status: true },
            { feature: "NPWP Yayasan", status: true },
            { feature: "Surat Keterangan Terdaftar Pajak Yayasan (SKT)", status: true },
            { feature: "Nomor Induk Berusaha (NIB)", status: true },
            { feature: "Pernyataan Mandiri OSS (K3L, Tata Ruang dan SPPL)", status: true },
            { feature: "Sertifikat Standar (Jika resiko KBLI Menengah Rendah)", status: true },
            { feature: "Hak Akses OSS", status: true },
            { feature: "Free Email Firma Hukum", status: true },
            { feature: "Free Stempel Firma Hukum", status: true }
        ]
    },
];

export const ExtrasPackages = [
    {
        type: "Pengurusan PKP (Pengusaha Kena Pajak)",
        highlight: false,
        price: 1500000,
        priceOriginal: 2500000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pengurusan%20PKP%20nih!%20",
        discount: 40,
        features: [
            { feature: "Free Consultasi", status: true },
            { feature: "SPPKP (Surat Pengukuhan Pengusaha Kena Pajak)", status: true },
            { feature: "Sertifikat Elektronik (SE)", status: true }
        ]
    },
    {
        type: "Pengurusan NIB (Nomor Induk Berusaha)",
        highlight: false,
        price: 500000,
        priceOriginal: 1000000,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pengurusan%20NIB%20nih!%20",
        discount: 50,
        features: [
            { feature: "NIB (Nomor Induk Berusaha)", status: true },
            { feature: "Pernyataan Mandiri (K3L, SPPL dan Tata Ruang)", status: true },
            { feature: "Sertifikat Standar (Jika Skala Resiko Menengah Rendah)", status: true },
            { feature: "Hak Akses OSS", status: true }
        ]
    }
]

export const VOPAckages = [
    {
        type: "Virtual Office",
        highlight: false,
        price: 2652000,
        priceOriginal: 4163640,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20Pendirian%20Virtual%20Office%20nih!%20",
        discount: 36,
        features: [
            { feature: "Perjanjian Sewa Menyewa 1 Tahun", status: true },
            { feature: "Sudah Termasuk PPN dan PPH", status: true },
            { feature: "Alamat Virtual Office Bisa PKP", status: true },
            { feature: "Bisa Pakai Ruang Meeting diseluruh Cabang Virtual Office", status: true },
            { feature: "Layanan Surat Menyurat", status: true },
            { feature: "Notifikasi Atas Dokumen Atau Surat Masuk", status: true },
            { feature: "Free Surat Domisili Gedung", status: true },
            { feature: "Free Wifi", status: true },
            { feature: "Self Service Pantry", status: true },
            { feature: "Alamat Komersil dan Prestisius", status: true },
            { feature: "Bonus Meeting Room Gratis 60-90 Jam Pertahun", status: true },
            { feature: "Fasilitas Live Streaming", status: true },
            { feature: "Fasilitas Podcast", status: true },
            { feature: "Fasilitas Proyektor", status: true }
        ]
    },
]