export const WebPackages = [
    {
        type: "Mini Web Company Profile",
        price: 1200000,
        priceOriginal: 1716000,
        discount: 30,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
        features: [
            { feature: "1 Page", status: true },
            { feature: "Domain Included", status: true },
            { feature: "SEO Friendly", status: true },
            { feature: "Design Premium", status: true },
            { feature: "Design Responsive", status: true },
            { feature: "Lifetime Support & Maintenance Teknis", status: true },
            { feature: "Content Writing", status: true },
            { feature: "SSL Included (Https)", status: true },
            { feature: "Revisi 2x", status: true },
            { feature: "Integrasi Sosial media", status: true },
            { feature: "Managed Server Data", status: false },
            { feature: "CMS Admin", status: false },
            { feature: "Free 1 Professional Email", status: false },
            { feature: "Free 10 Related Article Content", status: false },
            { feature: "Free 5 Design Product", status: false },
            { feature: "Login Owner & User", status: false },
            { feature: "Payment Gateway", status: false },
            { feature: "Client Request Feature", status: false }
        ]
    },
    {
        type: "Company Profile Basic",
        price: 2500000,
        priceOriginal: 3575000,
        discount: 30,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
        features: [
            { feature: "Up to 8 Page", status: true },
            { feature: "Domain Included", status: true },
            { feature: "SEO Friendly", status: true },
            { feature: "Design Premium", status: true },
            { feature: "Design Responsive", status: true },
            { feature: "Lifetime Support & Maintenance Teknis", status: true },
            { feature: "Content Writing", status: true },
            { feature: "SSL Included (Https)", status: true },
            { feature: "Revisi 2x", status: true },
            { feature: "Integrasi Sosial media", status: true },
            { feature: "Managed Server Data", status: false },
            { feature: "CMS Admin", status: false },
            { feature: "Free 1 Professional Email", status: false },
            { feature: "Free 10 Related Article Content", status: false },
            { feature: "Free 5 Design Product", status: false },
            { feature: "Login Owner & User", status: false },
            { feature: "Payment Gateway", status: false },
            { feature: "Client Request Feature", status: false }
        ]
    },
    {
        type: "Blog Static / Product Catalof",
        price: 4500000,
        priceOriginal: 6435000,
        discount: 30,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
        features: [
            { feature: "Dynamic Page", status: true },
            { feature: "Domain Included", status: true },
            { feature: "SEO Friendly", status: true },
            { feature: "Design Premium", status: true },
            { feature: "Design Responsive", status: true },
            { feature: "Lifetime Support & Maintenance Teknis", status: true },
            { feature: "Content Writing", status: true },
            { feature: "SSL Included (Https)", status: true },
            { feature: "Revisi 4x", status: true },
            { feature: "Integrasi Sosial media", status: true },
            { feature: "Managed Server Data", status: true },
            { feature: "1 Internal Admin", status: true },
            { feature: "Client Request Feature", status: true },
            { feature: "CMS Admin", status: false },
            { feature: "Free 1 Professional Email", status: false },
            { feature: "Free 10 Related Article Content", status: false },
            { feature: "Free 5 Design Product", status: false },
            { feature: "Login Owner & User", status: false },
            { feature: "Payment Gateway", status: false },
        ]
    },
    {
        type: "Dynamic Data Company Profile",
        price: 6900000,
        priceOriginal: 9867000,
        discount: 30,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
        features: [
            { feature: "Up to 15 Page", status: true },
            { feature: "Domain Included", status: true },
            { feature: "SEO Friendly", status: true },
            { feature: "Design Premium", status: true },
            { feature: "Design Responsive", status: true },
            { feature: "Lifetime Support & Maintenance Teknis", status: true },
            { feature: "Content Writing", status: true },
            { feature: "SSL Included (Https)", status: true },
            { feature: "Revisi 4x", status: true },
            { feature: "Integrasi Sosial media", status: true },
            { feature: "Managed Server Data", status: true },
            { feature: "CMS Admin", status: true },
            { feature: "Free 1 Professional Email", status: false },
            { feature: "Free 10 Related Article Content", status: false },
            { feature: "Free 5 Design Product", status: false },
            { feature: "Login Owner & User", status: false },
            { feature: "Payment Gateway", status: false },
            { feature: "Client Request Feature", status: false }
        ]
    },
    {
        type: "Company Blog Website",
        price: 8950000,
        priceOriginal: 12798500,
        discount: 30,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
        features: [
            { feature: "Dynamic Page", status: true },
            { feature: "Domain Included", status: true },
            { feature: "SEO Friendly", status: true },
            { feature: "Design Premium", status: true },
            { feature: "Design Responsive", status: true },
            { feature: "Lifetime Support & Maintenance Teknis", status: true },
            { feature: "Content Writing", status: true },
            { feature: "SSL Included (Https)", status: true },
            { feature: "Revisi 4x", status: true },
            { feature: "Integrasi Sosial media", status: true },
            { feature: "Managed Server Data", status: true },
            { feature: "CMS Admin", status: true },
            { feature: "Free 1 Professional Email", status: true },
            { feature: "Free 10 Related Article Content", status: true },
            { feature: "Login Owner Only", status: true },
            { feature: "Payment Gateway", status: false },
            { feature: "Client Request Feature", status: false }
        ]
    },
    {
        type: "Company Business E-Commerce",
        price: 24950000,
        priceOriginal: 47405000,
        discount: 30,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
        features: [
            { feature: "Dynamic Page", status: true },
            { feature: "Domain Included", status: true },
            { feature: "SEO Friendly", status: true },
            { feature: "Design Premium", status: true },
            { feature: "Design Responsive", status: true },
            { feature: "Lifetime Support & Maintenance Teknis", status: true },
            { feature: "Content Writing", status: true },
            { feature: "SSL Included (Https)", status: true },
            { feature: "Revisi 4x", status: true },
            { feature: "Integrasi Sosial media", status: true },
            { feature: "Managed Server Data", status: true },
            { feature: "CMS Admin", status: true },
            { feature: "Free 1 Professional Email", status: true },
            { feature: "Free 5 Design Product", status: true },
            { feature: "Login Owner & User", status: true },
            { feature: "Payment Gateway", status: true },
            { feature: "Client Request Feature", status: false }
        ]
    },
    {
        type: "Custom Web Client Request",
        price: 0,
        priceOriginal: 0,
        discount: 0,
        link: "https://api.whatsapp.com/send?phone=628887127000&text=Halo%20MinGans!%20Aku%20mau%20konsultasi%20terkait%20pembuatan%20Website%20nih!%20",
        features: [
            { feature: "Dynamic Page", status: true },
            { feature: "Domain Included", status: true },
            { feature: "SEO Friendly", status: true },
            { feature: "Design Premium", status: true },
            { feature: "Design Responsive", status: true },
            { feature: "Lifetime Support & Maintenance Teknis", status: true },
            { feature: "Content Writing", status: true },
            { feature: "SSL Included (Https)", status: true },
            { feature: "Revisi 4x", status: true },
            { feature: "Integrasi Sosial media", status: true },
            { feature: "Managed Server Data", status: true },
            { feature: "CMS Admin", status: true },
            { feature: "Free 1 Professional Email", status: true },
            { feature: "Free Design Or Content", status: true },
            { feature: "Login Owner & User", status: true },
            { feature: "Payment Gateway", status: true },
            { feature: "Client Request Feature", status: true }
        ]
    }
];
